name: deployment workflow to CloudHub 2.0

on:
  workflow_call:
    inputs:
      environment:
        required: true
        description: github actions environment to use valiarbles, secrets and rules 
        type: string

jobs:
  deploy-to-ch20:
    runs-on: ubuntu-latest

    environment: ${{ inputs.environment }}

    steps:
    #checkout the source code from the git repo
    - uses: actions/checkout@v3

    #caches maven dependencies
    - uses: actions/cache@v3
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-

    #setup java 1.8
    - name: Set up JDK 1.8
      uses: actions/setup-java@v3
      with:
        distribution: 'zulu'
        java-version: '8'

    #create settings.xml file with the connected app credentials
    - name: Create settings.xml
      uses: whelk-io/maven-settings-xml-action@v21
      with:
        servers: >
          [
            {
              "id": "AP-Repository",
              "username": "~~~Client~~~",
              "password": "${{ secrets.CA_CLIENTID }}~?~${{ secrets.CA_CLIENTSECRET }}"

            },
            {
              "id": "anypoint-exchange-v3",
              "username": "~~~Client~~~",
              "password": "${{ secrets.CA_CLIENTID }}~?~${{ secrets.CA_CLIENTSECRET }}"

            }
          ]

    - name: Deploy to CH2.0
      run: |
        mvn deploy -DskipTests -DmuleDeploy \
          -DconnectedApp.clientId=${{ secrets.CA_CLIENTID }} \
          -DconnectedApp.clientSecret=${{ secrets.CA_CLIENTSECRET }} \
          -Dmule.env=${{ vars.ENV }} \
          -Dprivate.space.name="${{ vars.CH2_TARGET }}" \
          -Denvironment=${{ vars.AP_ENVIRONMENT }}\
          -Dch2.replicas=${{ vars.DEPLOYMENT_REPLICAS }} \
          -Dch2.vCores=${{ vars.CH2_VCORES }} \
          -Dmule.encryption.key=${{ secrets.ENCRYPTION_KEY }} \
          -Danypoint.client_id=${{ secrets.AP_CLIENTID }} \
          -Danypoint.client_secret=${{ secrets.AP_CLIENTSECRET }} 